# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_library(
    name = "rental_manager",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//user:__pkg__"],
)